# Generated by Django 3.2.5 on 2021-07-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_investmnet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='investmnet',
            new_name='investment',
        ),
    ]
